// <copyright file="AttributeConstants.cs" company="OhFlowi">
// Copyright (c) OhFlowi. All rights reserved.
// </copyright>

namespace FusionReactor.SourceGenerators.EnumExtensions.Constants;

/// <summary>
/// Contains constants related to the GenerateEnumExtensions attribute.
/// </summary>
public static class AttributeConstants
{
    /// <summary>
    /// The name of the GenerateEnumExtensions attribute.
    /// </summary>
    public const string Name = "GenerateEnumExtensionsAttribute";

    /// <summary>
    /// The namespace for the GenerateEnumExtensions attribute.
    /// </summary>
    public const string Namespace = "FusionReactor.SourceGenerators.EnumExtensions";

    /// <summary>
    /// The full name representation of the GenerateEnumExtensions attribute, including namespace and name.
    /// </summary>
    public const string FullName = Namespace + "." + Name;

    /// <summary>
    /// The file name for the generated enum extensions.
    /// </summary>
    public const string FileName = Name + ".g.cs";

    /// <summary>
    /// The content of the generated enum extensions file.
    /// </summary>
    public const string Content =
        @"
        // <auto-generated />

        namespace " + Namespace + @";

        using System;
        using System.CodeDom.Compiler;

        /// <summary>
        /// Attribute to indicate that extensions should be generated for the decorated enum.
        /// </summary>
        [GeneratedCode(""" + nameof(FusionReactor) + @""", null)]
        [AttributeUsage(AttributeTargets.Enum)]
        public class " + Name + @" : Attribute
        {
        }
        ";
}
