// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

namespace FusionReactor.SourceGenerators.EnumExtensions.Constants;

/// <summary>
/// Constants related to the "GenerateEnumExtensionsAttributeAttribute".
/// </summary>
public static class DisplayResultConstants
{
    /// <summary>
    /// The name of the EnumsFastAttribute.
    /// </summary>
    public const string Name = "DisplayResult";

    /// <summary>
    /// The content of the EnumsFastAttribute.
    /// </summary>
    public const string Content =
        """
        // <auto-generated />

        #nullable enable

        using System;
        using System.CodeDom.Compiler;

        namespace FusionReactor.SourceGenerators.EnumExtensions;

        /// <inheritdoc cref = "System.ComponentModel.DataAnnotations.DisplayAttribute"/>
        [GeneratedCode("FusionReactor.SourceGenerators.EnumExtensions", null)]
        public class DisplayResult
        {
            /// <summary>
            /// Gets or sets the ShortName attribute property, which may be a resource key string.
            /// <para>
            /// Consumers must use the <see cref = "GetShortName"/> method to retrieve the UI display string.
            /// </para>
            /// </summary>
            /// <remarks>
            /// The property contains either the literal, non-localized string or the resource key
            /// to be used in conjunction with <see cref = "ResourceType"/> to configure a localized
            /// short name for display.
            /// <para>
            /// The <see cref = "GetShortName"/> method will return either the literal, non-localized
            /// string or the localized string when <see cref = "ResourceType"/> has been specified.
            /// </para>
            /// </remarks>
            /// <value>
            /// The short name is generally used as the grid column label for a UI element bound to the member
            /// bearing this attribute.  A <c>null</c> or empty string is legal, and consumers must allow for that.
            /// </value>
            public string? ShortName { get; set; }
            /// <summary>
            /// Gets or sets the Name attribute property, which may be a resource key string.
            /// <para>
            /// Consumers must use the <see cref = "GetName"/> method to retrieve the UI display string.
            /// </para>
            /// </summary>
            /// <remarks>
            /// The property contains either the literal, non-localized string or the resource key
            /// to be used in conjunction with <see cref = "ResourceType"/> to configure a localized
            /// name for display.
            /// <para>
            /// The <see cref = "GetName"/> method will return either the literal, non-localized
            /// string or the localized string when <see cref = "ResourceType"/> has been specified.
            /// </para>
            /// </remarks>
            /// <value>
            /// The name is generally used as the field label for a UI element bound to the member
            /// bearing this attribute.  A <c>null</c> or empty string is legal, and consumers must allow for that.
            /// </value>
            public string? Name { get; set; }
            /// <summary>
            /// Gets or sets the Description attribute property, which may be a resource key string.
            /// <para>
            /// Consumers must use the <see cref = "GetDescription"/> method to retrieve the UI display string.
            /// </para>
            /// </summary>
            /// <remarks>
            /// The property contains either the literal, non-localized string or the resource key
            /// to be used in conjunction with <see cref = "ResourceType"/> to configure a localized
            /// description for display.
            /// <para>
            /// The <see cref = "GetDescription"/> method will return either the literal, non-localized
            /// string or the localized string when <see cref = "ResourceType"/> has been specified.
            /// </para>
            /// </remarks>
            /// <value>
            /// Description is generally used as a tool tip or description a UI element bound to the member
            /// bearing this attribute.  A <c>null</c> or empty string is legal, and consumers must allow for that.
            /// </value>
            public string? Description { get; set; }
            /// <summary>
            /// Gets or sets the Prompt attribute property, which may be a resource key string.
            /// <para>
            /// Consumers must use the <see cref = "GetPrompt"/> method to retrieve the UI display string.
            /// </para>
            /// </summary>
            /// <remarks>
            /// The property contains either the literal, non-localized string or the resource key
            /// to be used in conjunction with <see cref = "ResourceType"/> to configure a localized
            /// prompt for display.
            /// <para>
            /// The <see cref = "GetPrompt"/> method will return either the literal, non-localized
            /// string or the localized string when <see cref = "ResourceType"/> has been specified.
            /// </para>
            /// </remarks>
            /// <value>
            /// A prompt is generally used as a prompt or watermark for a UI element bound to the member
            /// bearing this attribute.  A <c>null</c> or empty string is legal, and consumers must allow for that.
            /// </value>
            public string? Prompt { get; set; }
            /// <summary>
            /// Gets or sets the GroupName attribute property, which may be a resource key string.
            /// <para>
            /// Consumers must use the <see cref = "GetGroupName"/> method to retrieve the UI display string.
            /// </para>
            /// </summary>
            /// <remarks>
            /// The property contains either the literal, non-localized string or the resource key
            /// to be used in conjunction with <see cref = "ResourceType"/> to configure a localized
            /// group name for display.
            /// <para>
            /// The <see cref = "GetGroupName"/> method will return either the literal, non-localized
            /// string or the localized string when <see cref = "ResourceType"/> has been specified.
            /// </para>
            /// </remarks>
            /// <value>
            /// A group name is used for grouping fields into the UI.  A <c>null</c> or empty string is legal,
            /// and consumers must allow for that.
            /// </value>
            public string? GroupName { get; set; }
            /// <summary>
            /// Gets or sets the order in which this field should be displayed.  If this property is not set then
            /// the presentation layer will automatically determine the order.  Setting this property explicitly
            /// allows an override of the default behavior of the presentation layer.
            /// <para>
            /// Consumers must use the <see cref = "GetOrder"/> method to retrieve the value, as this property getter will throw
            /// an exception if the value has not been set.
            /// </para>
            /// </summary>
            /// <exception cref = "System.InvalidOperationException">
            /// If the getter of this property is invoked when the value has not been explicitly set using the setter.
            /// </exception>
            public int? Order { get; set; }
        }

        """;
}
