using FusionReactor.SourceGenerators.EnumExtensions.Generators.Strategies.Base;
using FusionReactor.SourceGenerators.EnumExtensions.Models;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace FusionReactor.SourceGenerators.EnumExtensions.Generators;

public static class BaseExtensionGenerator
{
    private static readonly IEnumerable<IExtensionGeneratorStrategy> Strategies = new[]
    {
        ContentStrategy.Factory,
        NamesStrategy.Factory,
        ValuesStrategy.Factory,
        GetContentStrategy.Factory,
        GetNameStrategy.Factory,
        GetNamesStrategy.Factory,
        GetValuesStrategy.Factory,
        //HasFlagFastStrategy.Factory,
        ParseStrategy.Factory,
        TryParseStrategy.Factory,
    };

    public static string Generate(IncrementalGeneratorInitializationContext context, EnumDefinition node)
    {
        var strategyResults = Strategies
            .Select(x => x.GetMethod(context, node));

        var stringBuilder = new StringBuilder();

        foreach (var strategyResult in strategyResults)
        {
            stringBuilder.AppendLine(strategyResult);
        }

        var returnValue = new StringBuilder();

        returnValue.AppendLine("// <auto-generated />");
        returnValue.AppendLine();
        returnValue.AppendLine("#nullable enable");
        returnValue.AppendLine();
        returnValue.AppendLine("using System;");
        returnValue.AppendLine("using System.CodeDom.Compiler;");
        returnValue.AppendLine("using System.Collections;");
        returnValue.AppendLine("using System.Collections.Frozen;");
        returnValue.AppendLine("using System.Collections.Generic;");
        returnValue.AppendLine("using System.Collections.ObjectModel;");
        returnValue.AppendLine();
        returnValue.AppendLine($"namespace {node.Namespace};");
        returnValue.AppendLine();
        returnValue.AppendLine("/// <summary>");
        returnValue.AppendLine($"/// Extension methods for the <see cref=\"{node.Name}\"/> enum.");
        returnValue.AppendLine("/// </summary>");
        returnValue.AppendLine("[GeneratedCode(\"FusionReactor.SourceGenerators.EnumExtensions\", null)]");
        returnValue.AppendLine($"{node.Access} static partial class {node.Name}Extensions");
        returnValue.AppendLine("{");
        returnValue.AppendLine(stringBuilder.ToString());
        returnValue.AppendLine("}");
        returnValue.AppendLine();

        return CSharpSyntaxTree
            .ParseText(returnValue.ToString())
            .GetRoot()
            .NormalizeWhitespace()
            .ToFullString();
    }
}
