# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build (Debug)
      run: dotnet build --configuration Debug --no-restore
      
    - name: Test (Debug)
      run: dotnet test --configuration Debug --no-build --no-restore

    - name: Build (Release)
      run: dotnet build --configuration Release --no-restore

    - name: Test (Release)
      run: dotnet test --configuration Release --no-build --no-restore

    - name: Pack (Release)
      run: dotnet pack --configuration Release --output .\nuget --no-build --no-restore

    - name: Publish
      if: github.event_name == 'push'
      run: |
        if ( "${{github.ref}}" -match "^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+$" ) {
          dotnet nuget push .\nuget\*.nupkg -s nuget.org -k ${{secrets.NUGET_TOKEN}} --skip-duplicate
        } else {
          echo "publish is only enabled by tagging with a release tag"
        }
